#!/usr/bin/env node
// generates scripts/seed.sql — a pretend 3-day drive from Munich toward Lake Garda,
// so `npm run dev` has something cute to show. local dev only.

import { writeFileSync } from "node:fs";

const HOURS = 66;
const STEP_MIN = 20;
const now = Math.floor(Date.now() / 1000);
const start = now - HOURS * 3600;

// a handful of waypoints (lat, lon, rough elevation m)
const waypoints = [
  [48.135, 11.582, 520],   // munich
  [47.876, 11.343, 640],   // starnberg-ish
  [47.567, 11.096, 900],   // garmisch approach
  [47.425, 10.985, 1200],  // alpine pass
  [47.253, 11.393, 580],   // innsbruck
  [47.005, 11.507, 1370],  // brenner
  [46.716, 11.656, 560],   // brixen
  [46.498, 11.354, 260],   // bolzano
  [46.138, 11.072, 200],   // trento
  [45.884, 10.843, 90],    // riva del garda 💙
];

function lerp(a, b, t) { return a + (b - a) * t; }

const rows = [];
const total = Math.floor((HOURS * 60) / STEP_MIN);
for (let i = 0; i <= total; i++) {
  const t = i / total;
  const seg = Math.min(waypoints.length - 2, Math.floor(t * (waypoints.length - 1)));
  const local = t * (waypoints.length - 1) - seg;
  const [a, b] = [waypoints[seg], waypoints[seg + 1]];

  // wiggle so it looks like a road, not a ruler
  const wiggle = Math.sin(i * 1.7) * 0.002 + Math.sin(i * 0.41) * 0.004;
  const lat = lerp(a[0], b[0], local) + wiggle * 0.6;
  const lon = lerp(b[1], a[1], 1 - local) + wiggle;
  const ele = Math.round(lerp(a[2], b[2], local) + Math.sin(i * 0.9) * 25);

  const ts = start + i * STEP_MIN * 60;
  const hourOfDay = new Date(ts * 1000).getUTCHours() + 1;
  const daytime = hourOfDay >= 7 && hourOfDay <= 21;

  // overnight camp stops: park the van 22:00–08:00
  if (!daytime && i !== total) {
    if (hourOfDay === 22) rows.push({ ts, lat, lon, ele, parked: true });
    continue;
  }

  rows.push({ ts, lat, lon, ele, parked: false });
}

const values = rows.map((r, i) => {
  const temp = (18 - r.ele / 150 + Math.sin(i * 0.35) * 4).toFixed(1);
  const feels = (temp - 1.2).toFixed(1);
  const hum = Math.round(55 + Math.sin(i * 0.5) * 20);
  const wind = (8 + Math.abs(Math.sin(i * 0.23)) * 14).toFixed(1);
  const wcode = [0, 0, 1, 1, 2, 2, 3, 61][Math.abs(Math.round(Math.sin(i * 2.1) * 7))] ?? 1;
  const speed = r.parked ? 0 : Math.round(40 + Math.sin(i) * 25);
  const batt = Math.round(60 + Math.sin(i * 0.1) * 35);
  return `(${r.ts}, ${r.lat.toFixed(6)}, ${r.lon.toFixed(6)}, ${r.ele}, ${temp}, ${feels}, ${hum}, ${wind}, ${wcode}, ${speed}, ${batt})`;
});

const sql = `-- generated by scripts/make-seed.mjs — cute fake alpine road trip
DELETE FROM points;
INSERT OR IGNORE INTO points (ts, lat, lon, elevation_m, temp_c, feels_c, humidity, wind_kmh, weather_code, speed_kmh, battery) VALUES
${values.join(",\n")};
`;

writeFileSync(new URL("./seed.sql", import.meta.url), sql);
console.log(`🌱 wrote scripts/seed.sql with ${values.length} points`);
